
version: '2.1'
services:
  http-to-socks:
    build:
      context: .
      dockerfile: Dockerfile
      #args:
    image: ${DOCKER_REGISTRY:-home1oss}/privoxy:3.0.24
    restart: always
    container_name: ${HTTP_TO_SOCKS_DOMAIN:-http-to-socks}.${INFRASTRUCTURE:-local}
    hostname: ${HTTP_TO_SOCKS_DOMAIN:-http-to-socks}.${INFRASTRUCTURE:-local}
    ports:
    - "${HTTP_TO_SOCKS_PORT:-28118}:${HTTP_TO_SOCKS_PORT:-28118}/tcp"
    environment:
    - HTTP_TO_SOCKS_PORT=${HTTP_TO_SOCKS_PORT:-28118}
    - SOCKS_PROXY=${SOCKS_PROXY}
    volumes:
    - volume-http-to-socks:/var/log/privoxy
  smart-http-proxy:
    image: ${DOCKER_REGISTRY:-home1oss}/privoxy:3.0.24
    restart: always
    container_name: ${SMART_HTTP_PROXY_DOMAIN:-smart-http-proxy}.${INFRASTRUCTURE:-local}
    hostname: ${SMART_HTTP_PROXY_DOMAIN:-smart-http-proxy}.${INFRASTRUCTURE:-local}
    ports:
    - "${SMART_HTTP_PROXY_PORT:-28119}:${SMART_HTTP_PROXY_PORT:-28119}/tcp"
    environment:
    - SMART_HTTP_PROXY_PORT=${SMART_HTTP_PROXY_PORT:-28119}
    - UPSTREAM_PROXY_HOST_PORT=${HTTP_TO_SOCKS_DOMAIN:-http-to-socks}.${INFRASTRUCTURE:-local}:${HTTP_TO_SOCKS_PORT:-28118}
    volumes:
    - volume-smart-http-proxy:/var/log/privoxy

networks:
  default:
    external:
      name: oss-network

volumes:
  volume-http-to-socks: {}
  volume-smart-http-proxy: {}
